name: Test Github Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    container: ghdl/vunit:mcode-master
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run VUnit tests
        run: python3 ./and/test/run.py --xunit-xml vunit_results.xml

      - name: Upload simulation results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: simulation-artifacts (container)
          path: vunit_results.xml

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: "**/*.xml"
          check_name: VUnit Test Report (EnricoMi)
